title: "Joshua Addington"
author: "Joshua Addington"
description: "A portfolio to showcase projects and accomplishments."
email: "joshuaaddington@gmail.com"

projects:
  - title: "Minimalist Split Keyboard"
    description: "I built this keyboard as a personal project"
    url: "https://joshuaaddington.com/Split_Keyboard"
  - title: "Project Two"
    description: "Another amazing project."
    url: "https://joshuaaddington.com/PC_Case"
